version: '3'

services:

  db:
    container_name: cyber_db
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: cyber_app
    env_file: ./.env
    command: /app/run_app.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"

  celery:
    build: ./app
    command: celery -A core worker -l info
    env_file: ./.env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./app
    command: celery -A core beat -l info
    env_file: ./.env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
      - celery
      - celery-beat
      - app

#  nginx:
#    build: ./nginx
#    container_name: cyber_nginx
#    restart: always
#    env_file: ./.env
#    volumes:
#      - ./app/static_root:/code/static_root
#      - ./app/media:/code/media
#      - ./nginx/logs:/var/log/nginx
#      - ./nginx/letsencrypt:/code/letsencrypt
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - app


volumes:
  db_data: